# Generated by Django 4.2.3 on 2023-08-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, default='static/post_default.png', null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
            },
        ),
    ]
